name: IIITV Blog

markdown: kramdown
kramdown:
    input: GFM

fullpath: http://iiitv.github.io
description: IIITV Blog maintained by students
baseurl: 
permalink: /blog/:title.html
title: IIITV Blog

highlighter: rouge
# paginate: 5
# paginate_path: /page:num/

disqusid: blogiiitv
disqusurl: http://iiitv.github.io