name: IIITV Blog

markdown: redcarpet

fullpath: http://iiitv.github.io
description: IIITV Blog maintained by students
baseurl: 
permalink: /blog/:title.html
title: IIITV Blog

highlighter: pygments
paginate: 5
paginate_path: /page:num/
gems: [jekyll-paginate]

# Tagging
tag_page_layout: tag_page
tag_page_dir: tags

disqusid: blogiiitv
disqusurl: http://iiitv.github.io